### ISSUE TITLE
Issue With Maintaining Pane Selection on Swap

### ISSUE THREAD

**Issue by Akamaozu** [raguay/SwapPanels#3]
Tried to implement a solution for [this issue](https://github.com/fman-users/fman/issues/318#issuecomment-365307576) because it seemed simple and useful enough.

In testing, I noticed the Swap command will occasionally throw an error stating that the file in selection doesn't exist, even though it does.

Suspecting this is an fman api issue (cc. @mherrmann).

Here's my branch: https://github.com/Akamaozu/SwapPanels/tree/keep-selection

Here's the error:
![image](https://user-images.githubusercontent.com/1587024/36219993-270e7e42-1187-11e8-840d-0f487fdf2988.png)

![swap crash](https://user-images.githubusercontent.com/1587024/36220140-92345ac0-1187-11e8-80df-3bfc5dcd5101.gif)

**Comment by raguay** [comment]
Yes. The issue is that the command to select the files in the new panel
will happen before the panels are actually swapped. This is due to the
script executes faster than the UI keeps up with it. The only fix would be
for the specification of the panel address finish with the UI update before
returning to the rest of the script. But, that is a low level
implementation. That is way I haven't added that feature (plus I don't
really make use of that feature).

**Comment by mherrmann** [comment]
I believe this can be solved with the `callback` parameter of [DirectoryPane.set_path(...)](https://fman.io/docs/api#DirectoryPane.set_path). Let me know if you'd like me to go into more detail!

**Comment by raguay** [comment]
Oh. I didn't notice it had a callback. Was that added recently or did I
just miss it? That should help.

Richard

On Thu, Feb 15, 2018 at 10:07 PM, Michael Herrmann <notifications@github.com

**Comment by raguay** [comment]
Just tried it with the callbacks. I don't get the error all the time, but
here and there it still errors. Happens more with the system loaded. Seems
to still be an issue with UI not catching up completely. I'll commit my
changes so that you can see them.

Richard

**Comment by raguay** [comment]
I added a sleep to the code with callbacks. It now always works, but does point out that the callbacks are called too soon.

**Comment by mherrmann** [comment]
The `callback` parameter has always been there :-) I believe you were still getting the exceptions because `_setRightPaneSelections` sets the cursor and selection in `lpane`. Shouldn't it work with `rpane` instead?

**Comment by raguay** [comment]
The current script doesn't get any excepts. The exceptions only happen when I take out the try..except statements with the sleep(). When those are gone, exceptions happen sometimes, especially when the system is loaded down (which is most of the time for me). Therefore, there is still a timing issue.

It sets the old right pane items in the left pane object. That in order to get the switch around.

**Comment by mherrmann** [comment]
Yes, I can imagine it not getting any excepts now. I meant without the `try ... except`.

I believe the correct solution is to

1. Remove the `try ... except` clauses
2. Replace `lpane.set_path(rpane_path, _setLeftPaneSelections)` by `lpane.set_path(rpane_path, _setRightPaneSelections)` (and vice versa).

With these changes, I am no longer getting exceptions.

**Comment by mherrmann** [comment]
(To be more precise: I was able to reproduce the exceptions after 1. But when I then do 2., they disappear.)

**Comment by raguay** [comment]
Hi,
The SwapPanel script is now set the way you mentioned above. For it, it throughs an except every 3-4 time used. Look at the code here to see if it is what you said (I believe it is). For my system, it still errors out.

I'm only using it on a mac right now. If you are testing on Linux, it might be a behavior across oses that we are seeing.

**Comment by mherrmann** [comment]
Thanks, I made a mistake in my comment above. The [last two lines of the code](https://github.com/raguay/SwapPanels/blob/6d440f7d3a47b7e3b8b4d7bc6e2ad88714b65632/swappanels/__init__.py#L37) should be

    lpane.set_path(rpane_path, _setRightPaneSelections)
    rpane.set_path(lpane_path, _setLeftPaneSelections)

The idea is that if you call `ABC.set_path(..., callback)` then `callback` should only access `ABC`.

**Comment by raguay** [comment]
I got it right now. Just updated it and created a new release for it. It would work fine now. Sorry for the confusion. I have my mind around it wrong.

**Comment by mherrmann** [comment]
Cool! If you're interested in a final tweak, I believe you can remove the `if(lpane_selection)` ([link](https://github.com/raguay/SwapPanels/blob/d86e1e130062b55f40cb5fe09a681a5d82f54df6/swappanels/__init__.py#L22)):

    def _setLeftPaneSelections():
        rpane.place_cursor_at(lpane_cursor)
        for url in lpane_selection:
            rpane.toggle_selection(url)

The reason is that `for x in thelist` simply has no effect when `thelist` is empty, and [get_selected_files()](https://fman.io/docs/api#DirectoryPane.get_selected_files) guarantees to return the empty list when no files are selected.

**Comment by raguay** [comment]
Okay. I did the final tweek as well. I'm used to having to check for other language.

**Comment by ababak** [comment]
I was playing with swapping the panels and it worked fine until I pressed Shift-P several times too fast:

Command 'SwapPanel' raised error.

```
Traceback (most recent call last):
  File "fman\impl\plugins\plugin.py", line 289, in _run_in_thread
  File "C:\Users\a.babak\AppData\Roaming\fman\Plugins\Third-party\SwapPanels\swappanels\__init__.py", line 36, in __call__
    lpane.set_path(rpane_path, _setRightPaneSelections)
  File "fman\__init__.py", line 107, in set_path
  File "fman\impl\util\qt\thread.py", line 11, in result
  File "fman\impl\util\qt\thread.py", line 58, in run_in_thread
  File "fman\impl\util\qt\thread.py", line 83, in result
  File "fman\impl\util\qt\thread.py", line 71, in __call__
  File "fman\impl\widgets.py", line 107, in set_location
  File "fman\impl\model\__init__.py", line 550, in set_location
  File "fman\impl\model\__init__.py", line 174, in set_location
  File "C:\Users\a.babak\AppData\Roaming\fman\Plugins\Third-party\SwapPanels\swappanels\__init__.py", line 26, in _setRightPaneSelections
    lpane.place_cursor_at(rpane_cursor)
  File "fman\__init__.py", line 101, in place_cursor_at
  File "fman\impl\util\qt\thread.py", line 11, in result
  File "fman\impl\util\qt\thread.py", line 43, in run_in_thread
  File "fman\impl\widgets.py", line 113, in place_cursor_at
  File "fman\impl\view.py", line 289, in place_cursor_at
  File "fman\impl\view.py", line 390, in _get_index
  File "fman\impl\model\__init__.py", line 200, in find
ValueError: None is not in list
```

**Comment by raguay** [comment]
You went faster than the UI could keep up. Fman doesn't stop keystrokes to
wait for the UI. In real life, you wouldn't be swapping sides that fast.

The only way to fix that is to stop keystroke execution while UI is
updating. That could cause fman act sluggish in some instances. That would
be an fman issue more than an issue with the plugin.

**Comment by ababak** [comment]
The solution could be to ignore the new swap if the old one has not been finished.

**Comment by raguay** [comment]
I just found one more issue. It should now work all the time without having to wait on anything. Give it a try.

**Comment by ababak** [comment]
It works much faster!

Although I was still able to catch that error))

```
Command 'SwapPanel' raised error.

Traceback (most recent call last):
  File "fman\impl\plugins\plugin.py", line 289, in _run_in_thread
  File "C:\Users\a.babak\AppData\Roaming\fman\Plugins\Third-party\SwapPanels\swappanels\__init__.py", line 37, in __call__
    lpane.set_path(rpane_path, _setRightPaneSelections)
  File "fman\__init__.py", line 107, in set_path
  File "fman\impl\util\qt\thread.py", line 11, in result
  File "fman\impl\util\qt\thread.py", line 58, in run_in_thread
  File "fman\impl\util\qt\thread.py", line 83, in result
  File "fman\impl\util\qt\thread.py", line 71, in __call__
  File "fman\impl\widgets.py", line 107, in set_location
  File "fman\impl\model\__init__.py", line 550, in set_location
  File "fman\impl\model\__init__.py", line 174, in set_location
  File "C:\Users\a.babak\AppData\Roaming\fman\Plugins\Third-party\SwapPanels\swappanels\__init__.py", line 27, in _setRightPaneSelections
    lpane.place_cursor_at(rpane_cursor)
  File "fman\__init__.py", line 101, in place_cursor_at
  File "fman\impl\util\qt\thread.py", line 11, in result
  File "fman\impl\util\qt\thread.py", line 43, in run_in_thread
  File "fman\impl\widgets.py", line 113, in place_cursor_at
  File "fman\impl\view.py", line 289, in place_cursor_at
  File "fman\impl\view.py", line 390, in _get_index
  File "fman\impl\model\__init__.py", line 200, in find
ValueError: 'file://C:/Users/a.babak/AppData/Roaming/fman/Local' is not in list

```

**Comment by raguay** [comment]
Yes. If you go very fast swapping back and forth, you will hit a race
condition where the UI still hasn't caught up and a second key press
happens. There is no real easy way around that other than disallowing key
presses from happening too often. But, that is best handled by fman and not
a plugin.

Realistically, why would anyone need to swap panels that fast and that
often. Just normal use should never see this condition.

**Comment by raguay** [comment]
Okay. I implemented a key debouncing system to keep the race condition from happening. I press on the hotkey for five minutes without crashing. So, it should be fine now. It was a blur switching though.

**Comment by ababak** [comment]
Works fine now. Here's the workaround I've made before I saw yours:

`from fman import DirectoryPaneCommand


class SwapPanel(DirectoryPaneCommand):
    
    def __init__(self, *args, **kw):
        super(SwapPanel, self).__init__(*args, **kw)
        self.busy = False

    def __call__(self):
        if self.busy:
            return
        self.busy = True
        panes = self.pane.window.get_panes()

        currentPane = self.pane
        lpane = panes[0]
        lpane_path = lpane.get_path()
        lpane_selection = lpane.get_selected_files()
        lpane_cursor = lpane.get_file_under_cursor()

        rpane = panes[1]
        rpane_path = rpane.get_path()
        rpane_selection = rpane.get_selected_files()
        rpane_cursor = rpane.get_file_under_cursor()

        def _setLeftPaneSelections():
            if lpane_cursor is not None:
                rpane.place_cursor_at(lpane_cursor)
            for url in lpane_selection:
                rpane.toggle_selection(url)

        def _setRightPaneSelections():
            if rpane_cursor is not None:
                lpane.place_cursor_at(rpane_cursor)
            for url in rpane_selection:
                lpane.toggle_selection(url)

            if panes[0] == currentPane:
                panes[1].focus()
            else:
                panes[0].focus()
            self.busy = False

        rpane.set_path(lpane_path, _setLeftPaneSelections)
        lpane.set_path(rpane_path, _setRightPaneSelections)
`
